require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookingCitiesController do

  # This should return the minimal set of attributes required to create a valid
  # BookingCity. As you add validations to BookingCity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookingCitiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all booking_cities as @booking_cities" do
      booking_city = BookingCity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:booking_cities).should eq([booking_city])
    end
  end

  describe "GET show" do
    it "assigns the requested booking_city as @booking_city" do
      booking_city = BookingCity.create! valid_attributes
      get :show, {:id => booking_city.to_param}, valid_session
      assigns(:booking_city).should eq(booking_city)
    end
  end

  describe "GET new" do
    it "assigns a new booking_city as @booking_city" do
      get :new, {}, valid_session
      assigns(:booking_city).should be_a_new(BookingCity)
    end
  end

  describe "GET edit" do
    it "assigns the requested booking_city as @booking_city" do
      booking_city = BookingCity.create! valid_attributes
      get :edit, {:id => booking_city.to_param}, valid_session
      assigns(:booking_city).should eq(booking_city)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookingCity" do
        expect {
          post :create, {:booking_city => valid_attributes}, valid_session
        }.to change(BookingCity, :count).by(1)
      end

      it "assigns a newly created booking_city as @booking_city" do
        post :create, {:booking_city => valid_attributes}, valid_session
        assigns(:booking_city).should be_a(BookingCity)
        assigns(:booking_city).should be_persisted
      end

      it "redirects to the created booking_city" do
        post :create, {:booking_city => valid_attributes}, valid_session
        response.should redirect_to(BookingCity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved booking_city as @booking_city" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookingCity.any_instance.stub(:save).and_return(false)
        post :create, {:booking_city => { "name" => "invalid value" }}, valid_session
        assigns(:booking_city).should be_a_new(BookingCity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookingCity.any_instance.stub(:save).and_return(false)
        post :create, {:booking_city => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested booking_city" do
        booking_city = BookingCity.create! valid_attributes
        # Assuming there are no other booking_cities in the database, this
        # specifies that the BookingCity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BookingCity.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => booking_city.to_param, :booking_city => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested booking_city as @booking_city" do
        booking_city = BookingCity.create! valid_attributes
        put :update, {:id => booking_city.to_param, :booking_city => valid_attributes}, valid_session
        assigns(:booking_city).should eq(booking_city)
      end

      it "redirects to the booking_city" do
        booking_city = BookingCity.create! valid_attributes
        put :update, {:id => booking_city.to_param, :booking_city => valid_attributes}, valid_session
        response.should redirect_to(booking_city)
      end
    end

    describe "with invalid params" do
      it "assigns the booking_city as @booking_city" do
        booking_city = BookingCity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookingCity.any_instance.stub(:save).and_return(false)
        put :update, {:id => booking_city.to_param, :booking_city => { "name" => "invalid value" }}, valid_session
        assigns(:booking_city).should eq(booking_city)
      end

      it "re-renders the 'edit' template" do
        booking_city = BookingCity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookingCity.any_instance.stub(:save).and_return(false)
        put :update, {:id => booking_city.to_param, :booking_city => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested booking_city" do
      booking_city = BookingCity.create! valid_attributes
      expect {
        delete :destroy, {:id => booking_city.to_param}, valid_session
      }.to change(BookingCity, :count).by(-1)
    end

    it "redirects to the booking_cities list" do
      booking_city = BookingCity.create! valid_attributes
      delete :destroy, {:id => booking_city.to_param}, valid_session
      response.should redirect_to(booking_cities_url)
    end
  end

end
